### ISSUE TITLE
模块如果没有关联，那么查询会不会有问题，如下：

### ISSUE THREAD

**Issue by Nokecy** [liuxx001/BodeAbp#3]
https://github.com/liuxx001/BodeAbp/blob/master/src/modules/BodeAbp.Forum/Plates/Domain/PlateKeeper.cs
这里如果前端要获取管理员姓名，那该怎么做呢？

**Comment by liuxx-u** [comment]
模块本身不能查询其他模块数据，有这种需求可以在Controller中组装查询表达式，接口从Controller中出去，Controller中是可以引用多个模块的。

**Comment by liuxx-u** [comment]
也可以做冗余，但是管理员姓名修改了需要发送一个事件出来，这边模块也做对应的修改，感觉要麻烦许多。
